version: 0.0
os: linux

files:
  - source: /
    destination: e1/backend-project/

#permissions:
#  - object: ci-scripts
#    pattern: "**"
#    owner: ubuntu
hooks:
  #ApplicationStop:
    #- location: ci-scripts/stop.sh
    #  timeout: 1200
    #  runas: ubuntu
  AfterInstall:
    - location: ci-scripts/install.sh
      timeout: 1200
      runas: ubuntu
  ApplicationStart:
    - location: ci-scripts/start.sh
      timeout: 1200
      runas: ubuntu
