version: 0.0
os: linux

files:
  - source: ci-scripts/
    destination: ci-scripts/

hooks:
  ApplicationStop:
    - location: ci-scripts/stop.sh
      runas: root
  AfterInstall:
    - location: ci-scripts/install.sh
      runas: root
  ApplicationStart:
    - location: ci-scripts/start.sh
      runas: root
