version: 0.0
os: linux

files:
  - source: ci-scripts
    destination: e1/backend-project/ci-scripts/

permissions:
  - object: ci-scripts
    pattern: "**"
    owner: ubuntu
hooks:
  ApplicationStop:
    - location: ci-scripts/stop.sh
      timeout: 600
      runas: ubuntu
  AfterInstall:
    - location: ci-scripts/install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: ci-scripts/start.sh
      timeout: 600
      runas: ubuntu
