version: 0.0
os: linux

files:
  - source: /
    destination: ci-scripts/

hooks:
  ApplicationStop:
    - location: stop.sh
      runas: root
  AfterInstall:
    - location: install.sh
      runas: root
  ApplicationStart:
    - location: start.sh
      runas: root
