# Generated by Django 3.0.7 on 2020-08-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='board_alias',
            field=models.CharField(default='v', max_length=5),
            preserve_default=False,
        ),
    ]
