# Generated by Django 3.0.7 on 2020-08-20 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E0', '0002_boardmodel_board_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='board_alias',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='board_id',
            field=models.CharField(default='v', max_length=5, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='board_text',
            field=models.CharField(default='A place to discuss video games', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.CreateModel(
            name='ThreadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('thread_name', models.CharField(default='', max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E0.BoardModel')),
            ],
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E0.ThreadModel'),
            preserve_default=False,
        ),
    ]
