# Generated by Django 3.0.7 on 2020-08-20 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E0', '0003_auto_20200820_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='message',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='E0.MessageModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='user_nickname',
            field=models.CharField(default='Anonymous', max_length=20),
            preserve_default=False,
        ),
    ]
